Using existing test database for alias 'default'...
Found 4 test(s).
System check identified no issues (0 silenced).
F...
======================================================================
FAIL: test_total_price (order.tests.TestOrder.test_total_price)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Mohammad\Desktop\bprint\django-task\order\tests.py", line 16, in test_total_price
    self.assertEqual(order.total_price, 72.95)
AssertionError: 58.0 != 72.95

----------------------------------------------------------------------
Ran 4 tests in 0.046s

FAILED (failures=1)
Preserving test database for alias 'default'...
